---
title: "Graphics with ggplot2"
author: "lkm"
date: "March 12, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

# ggplot2 demo
```{r setup}
library(tidyverse)
library(ggthemes)
```

```{r myplot}
#today we will use the mpg dataframe in base R

head(mpg)

myplot<- ggplot(mpg, aes(x=displ, y=hwy)) 
myplot + geom_point(alpha= 0.4) #sets transparency of points to see if they are stacked



```

```{r plot2}

plot2 <- ggplot(mpg, aes(x=displ, y=hwy, color=class)) #added color into original aes argument in order to color the points
plot2 + geom_point()

```

# make a scatterplot of 'hwy' vs 'cty' with different size points representing each 'class' and different colors for each fuel type

```{r plot3}
plot3 <- ggplot(mpg, aes(x=hwy, y=cty))
plot3 + geom_point(aes(size=class, color=fl))
  #get warning tho because putting size to a factor doesn't really make much sense
```

```{r plot4}

plot4 <- ggplot(mpg, aes(x=displ, y=hwy)) #if mapped color here, would be mapping based on a variable (aka column in your data frame)
plot4 + geom_point(alpha=0.4, color="blue") #outside of aes call, you are telling it what color to make

plot4 + geom_point() + geom_smooth() #adds regression line to points
```

# Faceting 
```{r facet}

fplot <- ggplot(mpg, aes(x=displ, y=hwy, color=class))
fplot + geom_point() + facet_wrap(~manufacturer) #~col name to tell it what to facet by
```

# plot themes
```{r theme, echo=TRUE}

#package ggthemes has a bunch of other themes available to use

# can save themes to a variable for re-use!
mytheme <- theme_classic() + theme(text= element_text(size=16))

fplot + geom_point() + facet_wrap(~manufacturer) + theme_bw()
fplot + geom_point() + theme_tufte() #Tufte's minimalist theme

fplot + geom_point() + facet_wrap(~year) #year as columns
#vs
fplot + geom_point() + facet_grid(year~.) #year as rows

fplot + geom_point() + facet_grid(year~.) + theme_classic() 

ggsave("fplot.png", width = 5, height = 5)
```

# geoms- look at ways to visualize distributions of your data
```{r geoms, echo=TRUE}
  #drv= drive train = front wheel, rear wheel, 4 wheel
ggplot(mpg, aes(x=drv , y=hwy))+
  geom_jitter()

ggplot(mpg, aes(x=drv , y=hwy))+
  geom_boxplot()

ggplot(mpg, aes(x=drv , y=hwy))+
  geom_violin()


## geom_smooth - to run models on data, default is loess (smooth mean)
plot4 + geom_point() + geom_smooth()

```

#labels
```{r labs, echo= TRUE}
plot4 + geom_point() + mytheme +
  labs(title="Relationship btwn engine size and highway mileage (mpg)",
       x= "Engine size (liters displaced)",
       y= "Highway mileage (mpg)")

#to make fonts bigger, use theme(), here i used the mytheme created above and added it to this graph!
```

#barcharts 
```{r bars, echo=TRUE}

ggplot(mpg, aes(x=fl)) +
  geom_bar() #plots fl on x axis and counts on y axis, default stat
  
  #check ?geom_bar() *or any other geom* to see the default stat that is used


ggplot(mpg, aes(x=fl, fill=class)) + 
  geom_bar(position= "fill") #position will change how bar is stacked

```

